# Copyright (c) 2016-2020 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: cartographic modeling        
site_url: https://github.com/jeffhowarth/cartographic-modeling
site_author: Jeff Howarth
site_description: >-
  Bits and flows of spatial analysis with earth engine, whitebox, and other tools. 

# Repository
repo_name: jeffhowarth/cartographic-modeling
repo_url: https://github.com/jeffhowarth/cartographic-modeling
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2024 Jeff Howarth

# Configuration
theme:
  logo: assets/myIcon.png
  favicon: assets/myIcon.png
  name: material
  # custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en

  features:
    # - tabs
    - navigation.instant
    - navigation.instant.progress  
    # - navigation.sections
    - navigation.indexes 
    - navigation.footer 

    # - navigation.expand 
    - content.code.copy

  palette:
    scheme: default
    primary: black
    accent: orange
  font:
    text: Helvetica   
    # text: Didact Gothic
    code: Roboto Mono

extra_css:
  - extra.css

# Plugins
plugins:
  - search
  - minify

# src and site directories
docs_dir: 'src'
site_dir: 'docs'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jeffhowarth
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jeffgeographer

# Extensions
markdown_extensions:
  - smarty
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: false
      toc_depth: 4
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx-inline
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
# Page tree
nav:
  - introduction: index.md  
  - CONCEPTS:  
    - spatial: concepts/spatial.md  
    - planning: concepts/planning.md  
    - change: concepts/change.md     
    - data models: concepts/data-models.md    
  - METHODS EE:  
    - introduction: methods/intro.md
    - load modules: methods/load-modules.md  
    - load data: methods/load-data.md  
    - inspect properties: methods/inspect-properties.md  
    - map layers: methods/map-layers.md  
    - filter data: methods/filter-data.md  
    - convert data model: methods/convert-data-model.md  
    - area operations: methods/area.md  
    - distance operations: methods/distance.md  
    - aggregate table: methods/aggregate-table.md  
    - local - one layer: methods/local-one-layer.md  
    - local - two layers: methods/local-two-layers.md 
    - zonal operations: methods/zonal-operations.md  
    - terrain operations: methods/terrain.md  
    - viz: methods/image-viz.md  
    - naip images: methods/naip.md 
    - export: methods/export.md  
  - METHODS WB:
    - hello whitebox: wb-methods/hello-whitebox.md  
    - mama raster: wb-methods/mama-raster.md  
  - METHODS Q:  
    - google base maps: q-methods/add-google-xyz.md  
    - vermont lidar: q-methods/vermont-lidar.md  
    - custom palettes: q-methods/custom-palettes.md  
  - PROBLEMS:  
    - area problems: problems/area-problems.md  
    - nominal problems: problems/nominal-problems.md  
    - proximity problems: problems/proximity-problems.md 
    - terrain problems: problems/terrain-problems.md 
  - WORKED FLOWS EE:  
    - area workflows: workflows/area-workflows.md  
    - nominal workflows: workflows/nominal-workflows.md  
    - proximity workflows: workflows/proximity-workflows.md    
    - terrain workflows: workflows/terrain-workflows.md   
  - CHALLENGES EE: 
    - clearings: challenges/clearings.md    
    - water story: challenges/water-story.md  
  - CHALLENGES WB:
    - workflow diagrams: challenges-wb/workflow-diagrams.md  
    - extract streams from dem: challenges-wb/extract-streams.md  
    - viewshed comparison: challenges-wb/viewshed-comparison.md  
    - least cost path: challenges-wb/least-cost-path.md  



  
#  - Contributing: contributing.md
#  - License: license.md

# # Google Analytics
# google_analytics:
#   - G-G4GWH4RPQ1
#   - auto
